baseURL = "https://larua-hugo.canitia.nl/"
languageCode = "en-us"
title = "Larua voor Hugo"
theme = "larua-hugo"
contentdir = "content/posts"
layoutdir = "layouts"
publishdir = "public"
canonifyurls = true

[[menu.main]]
    name = "Home"
    weight = 1
    url = "/"
[[menu.main]]
    name = "Blog"
    weight = 2
    url  = "/posts/"

